apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: cidr
        - name: MYSQL_USER
          value: cidr_dev
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-passwd
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-passwd
              optional: false
        image: mysql:8.0
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: 3306tcp33060
          protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeName: kmaster.example.com 
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data1/mysql
          type: ""
        name: mysql-data

