apiVersion: v1
kind: Pod 
metadata:
  name: network-tool
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: 
            - kmaster.example.com
  containers:
  - name: network-tool
    image: network-multitool:v1
