---
kind: Namespace
apiVersion: v1
metadata:
  name: network
  labels:
    name: network

---
apiVersion: v1
kind: Pod 
metadata:
  name: network-tool
  namespace: network
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            - kmaster.example.com 
  containers:
  - name: network-tool
    image: network-multitool:v1
