apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: centos
  name: centos
  namespace: monitoring
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - aks-agentpool-15187844-vmss000004
  containers:
  - image: centos:8
    name: centos
    command: ["/bin/sleep", "3650d"]
    resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 20Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}