# ---
# kind: Namespace
# apiVersion: v1
# metadata:
#   name: network
#   labels:
#     name: network

---
apiVersion: v1
kind: Pod 
metadata:
  name: network-tool
  namespace: argocd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            -  ip-10-114-200-5.cn-north-1.compute.internal
  containers:
  - name: network-tool
    image: praqma/network-multitool 
    resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 20Mi
