apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cli
  namespace: infotainment-backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
        app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          env:
            - name: database
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: database
            - name: host
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: host
            - name: jdbcUrl
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: jdbcUrl
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: password
            - name: port
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: port
            - name: username
              valueFrom:
                secretKeyRef:
                  name: prod-vehicle-music-apple-auth-db-replica
                  key: username
          resources:
            limits:
              cpu: '1'
              memory: 1G
            requests:
              cpu: 500m
              memory: 512M