apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  salad: {{ .Values.global.salad }}


{{- if .Values.ports }}
  {{- print "ports:" | nindent 2 }}
  {{- range .Values.ports }}
    - number: {{ . }}
      protocol: http
  {{- end }}
{{- end }}