apiVersion: v1
kind: Pod
metadata:
  name: network-tool
  labels: 
    name: network-tool
spec:
  containers:
  - name: network-tool
    image: network-multitool:v1
  nodeSelector:
    kubernetes.io/hostname: kmaster.example.com
