apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  tls:
    - hosts:
        - app.dev.aws.gravity.porsche.cn
      secretName: apps-tls
  rules:
  - host: app.dev.aws.gravity.porsche.cn
    http:
      paths:
        - path: /app(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: nginx-svc
              port:
                number: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 801719121160.dkr.ecr.cn-north-1.amazonaws.com.cn/nginx
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 100Mi
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
