apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: my-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
          items:
          - key: default.conf
            path: default.conf
      containers:
      - name: nginxhttps
        image: nginx:v1 
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/nginx/ssl"
          name: secret-volume
        - mountPath: "/etc/nginx/conf.d"
          name: configmap-volume
